# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 159cab152bb11b94a27a9b813e24748d2ad5bcedfdaea7a6d1ef46ca96adf8141e0805febedfca694cb296fd99c2c26de3bfdb8fab4789cbef649b1eef2d94d0

test:
  secret_key_base: 71cc4e39c8f8c96ab7e8575afe143e1f3dd82e9706a8e8618f851d66e095f0574db347481e987d12994d764f5be9d72c3517f4d8bbb0edb5865796ad57518cad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
